name: Shopkeepers-BlueMap
version: '${pluginVersion}'
authors: [blablubbabc]
website: '${dboUrl}'
description: '${description}'

main: de.blablubbabc.shopkeepers.bluemap.ShopkeepersBlueMapPlugin
depend: [Shopkeepers, BlueMap]
