name: Shopkeepers-BlueMap
version: '${pluginVersion}'
authors: [blablubbabc]
website: '${pluginUrl}'
description: '${pluginDescription}'

main: de.blablubbabc.shopkeepers.bluemap.ShopkeepersBlueMapPlugin
api-version: '1.21.5'
depend: [Shopkeepers, BlueMap]

commands:
    shopkeepers-bluemap:
        description: Base for all Shopkeepers-BlueMap commands.
        aliases: [shopkeeper-bluemap, skbm]
        usage: 'Unknown command! Try /<command> help'

permissions:
    shopkeepers-bluemap.help:
        description: Display the command help
        default: true
    shopkeepers-bluemap.reload:
        description: Reload the plugin
        default: op
